version: '3'
services:
  backend:
    build:
      context: ./backend
  frontend:
    build:
      context: ./frontend
  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      context: ./nginx
    ports:
      - 5000:80